# Generated by Django 4.0.3 on 2022-03-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='phone_number',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
