# Generated by Django 4.0.3 on 2022-04-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_email_project_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organisation',
            field=models.CharField(default='', max_length=120),
        ),
    ]
